### ISSUE TITLE
Can I use your code to make a radar system for planes and Helis?

### ISSUE THREAD

**Issue by Aaren882** [Sparker95/Arma-3-Ship-Sonar#4]
I want to use some of your codes to achieve my goal (I will mention they are made by you 😉)

**Comment by Sparker95** [comment]
Hi, yes sure, go ahead, I am curious what you will achieve. I am Sparker#0791 at Discord if you need me.

**Comment by Aaren882** [comment]
> Hi, yes sure, go ahead, I am curious what you will achieve. I am Sparker#0791 at Discord if you need me.

Thank you very much 😊
I will contact you if I need it
and thanks again love your works~
